language: node_js
node_js:
  - "6"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - xvfb

env:
  - CXX=g++-4.8

script:
  - npm test
  - npm run build
