language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "10"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  - CXX=g++-4.8

script:
  - npm run build
  - npm test
  - npm run release
