name: Meshprop Release Workflow

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12', '14', '15' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      
      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Tests
        run: npm test
              
      - name: Release
        run: npm run release
        env:
          node_pre_gyp_accessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          node_pre_gyp_secretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
